services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  frontend:
    # image: natjungquist/oursearch-frontend:arm64-latest #amd64 for VM, arm64 for Mac
    build: # building in DEV mode to avoid pushing new changes to image repo for now
      context: ./frontend
    ports:
      - "80"
    depends_on:
      - backend

  backend:
    # image: natjungquist/oursearch-backend:arm64-latest #amd64 for VM, arm64 for Mac
    build:
      context: ./backend
    ports:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/forum
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx:latest
    ports:
      - "80:80" # http
      # - "443:443" # https
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on: 
      - frontend
      - backend

volumes:
  db_data: 
    external: false