name: Format After Merge

on:
  push:
    branches:
      - main       # Run the workflow on pushes to the main branch (including merges)

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Google Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Apply formatting fixes after merge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

